name: Create Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build
              run: echo ${{ github.sha }} > release.txt
            - name: Test
              run: cat release.txt
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  generate_release_notes: true
                  body: ${{ github.event.commits[0].message }}
                  files: release.txt
                  draft: false
                  prerelease: false
